spring.application.name=redAi
spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
app.cors.allowed-origins=${FRONTEND_URL:http://localhost:5173}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

ai.provider=${AI_PROVIDER}
ai.api-key=${AI_API_KEY}
ai.api-url=${OPENAI_API_URL}
ai.model=${OPENAI_MODEL}
